# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from osmosis.gamm.pool_models.balancer.tx import tx_pb2 as osmosis_dot_gamm_dot_pool__models_dot_balancer_dot_tx_dot_tx__pb2


class MsgStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateBalancerPool = channel.unary_unary(
                '/osmosis.gamm.poolmodels.balancer.v1beta1.Msg/CreateBalancerPool',
                request_serializer=osmosis_dot_gamm_dot_pool__models_dot_balancer_dot_tx_dot_tx__pb2.MsgCreateBalancerPool.SerializeToString,
                response_deserializer=osmosis_dot_gamm_dot_pool__models_dot_balancer_dot_tx_dot_tx__pb2.MsgCreateBalancerPoolResponse.FromString,
                )


class MsgServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateBalancerPool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MsgServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateBalancerPool': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateBalancerPool,
                    request_deserializer=osmosis_dot_gamm_dot_pool__models_dot_balancer_dot_tx_dot_tx__pb2.MsgCreateBalancerPool.FromString,
                    response_serializer=osmosis_dot_gamm_dot_pool__models_dot_balancer_dot_tx_dot_tx__pb2.MsgCreateBalancerPoolResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'osmosis.gamm.poolmodels.balancer.v1beta1.Msg', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Msg(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateBalancerPool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/osmosis.gamm.poolmodels.balancer.v1beta1.Msg/CreateBalancerPool',
            osmosis_dot_gamm_dot_pool__models_dot_balancer_dot_tx_dot_tx__pb2.MsgCreateBalancerPool.SerializeToString,
            osmosis_dot_gamm_dot_pool__models_dot_balancer_dot_tx_dot_tx__pb2.MsgCreateBalancerPoolResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
