"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import grpc
import osmosis.gamm.pool_models.balancer.tx.tx_pb2

class MsgStub:
    def __init__(self, channel: grpc.Channel) -> None: ...
    CreateBalancerPool: grpc.UnaryUnaryMultiCallable[
        osmosis.gamm.pool_models.balancer.tx.tx_pb2.MsgCreateBalancerPool,
        osmosis.gamm.pool_models.balancer.tx.tx_pb2.MsgCreateBalancerPoolResponse,
    ]

class MsgServicer(metaclass=abc.ABCMeta):
    @abc.abstractmethod
    def CreateBalancerPool(
        self,
        request: osmosis.gamm.pool_models.balancer.tx.tx_pb2.MsgCreateBalancerPool,
        context: grpc.ServicerContext,
    ) -> osmosis.gamm.pool_models.balancer.tx.tx_pb2.MsgCreateBalancerPoolResponse: ...

def add_MsgServicer_to_server(servicer: MsgServicer, server: grpc.Server) -> None: ...
