# Generated by protobuf_init. Do not edit manually.
from .gov_pb2 import SetSuperfluidAssetsProposal
from .gov_pb2 import RemoveSuperfluidAssetsProposal
from .gov_pb2 import UpdateUnpoolWhiteListProposal
