"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import osmosis.mint.v1beta1.mint_pb2
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class GenesisState(google.protobuf.message.Message):
    """GenesisState defines the mint module's genesis state."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MINTER_FIELD_NUMBER: builtins.int
    PARAMS_FIELD_NUMBER: builtins.int
    REDUCTION_STARTED_EPOCH_FIELD_NUMBER: builtins.int
    @property
    def minter(self) -> osmosis.mint.v1beta1.mint_pb2.Minter:
        """minter is an abstraction for holding current rewards information."""
    @property
    def params(self) -> osmosis.mint.v1beta1.mint_pb2.Params:
        """params defines all the paramaters of the mint module."""
    reduction_started_epoch: builtins.int
    """reduction_started_epoch is the first epoch in which the reduction of mint
    begins.
    """
    def __init__(
        self,
        *,
        minter: osmosis.mint.v1beta1.mint_pb2.Minter | None = ...,
        params: osmosis.mint.v1beta1.mint_pb2.Params | None = ...,
        reduction_started_epoch: builtins.int = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["minter", b"minter", "params", b"params"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["minter", b"minter", "params", b"params", "reduction_started_epoch", b"reduction_started_epoch"]) -> None: ...

global___GenesisState = GenesisState
