"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class Params(google.protobuf.message.Message):
    """Params defines the parameters for the ibc-rate-limit module."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CONTRACT_ADDRESS_FIELD_NUMBER: builtins.int
    contract_address: builtins.str
    def __init__(
        self,
        *,
        contract_address: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["contract_address", b"contract_address"]) -> None: ...

global___Params = Params
